# Generated by Django 5.0.3 on 2024-03-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proteins',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('seq_region', models.CharField(blank=True, max_length=50, null=True)),
                ('id', models.CharField(blank=True, max_length=255, null=True)),
                ('cds_start', models.IntegerField(blank=True, null=True)),
                ('cds_end', models.IntegerField(blank=True, null=True)),
                ('dbxref', models.CharField(blank=True, max_length=700, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('protein_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'proteins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sequences',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('seq', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'db_table': 'sequences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('natural_host', models.CharField(blank=True, max_length=255, null=True)),
                ('lab_host', models.CharField(blank=True, max_length=255, null=True)),
                ('virus_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dbxref', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'species',
                'managed': False,
            },
        ),
    ]
