# Generated by Django 5.0.3 on 2024-04-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structures',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('pdb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.CharField(blank=True, max_length=255, null=True)),
                ('pdb_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'structures',
                'managed': False,
            },
        ),
    ]
